version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tasket}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./tasket-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-tasket}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PORT=${PORT:-5002}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./tasket-backend/uploads:/app/uploads

  # Frontend
  frontend:
    build:
      context: ./tasket
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      - PORT=${PORT:-3000}
    depends_on:
      - backend

volumes:
  postgres_data: