[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://your-backend-domain.railway.app/api"
  VITE_WS_BASE_URL = "https://your-backend-domain.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200